version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/commitato
permissions:
  - object: /home/ubuntu/commitato/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 60
      runas: ubuntu