spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commitato
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:user
            redirect-uri: "http://localhost:8080/login/callback"

jwt:
  secret: ${JWT_SECRET}
  aes-secret: ${AES_SECRET}
  iv-secret: ${IV_SECRET}

domain-uri: ${DOMAIN_URI}
