spring:
  application:
    name: commitato-BE

  datasource:
    url: jdbc:mysql://localhost:3306/commitato
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(ASdVann1K5quYxJ8tgdXIN7gbbrwVoJg6/7n/CArrUw=)
            client-secret: ENC(AG0Gj+dMJe9wW1oodMlWt/8ij8194wmBA6JBC5aU5x0Mlv5RKxAxcrPdgAkErkNLXJxWgEbWErw=)
            scope: read:user
            redirect-uri: http://localhost:8080/login

jwt:
  secret: ENC(C/OEDfd1jglCSGrQD+m08AgCUvny+kw0NCefjIXFfojJVnOZykF2k3+kNQi4vcU11ApypfQgD4nxMavffmZcBVZjjBNunC7DEneykZzSXgIxzedO+rxEh6ksJB7XvFge7yEusLE7XN4=)
  aes-secret: ENC(jOy8CXIurVIJVLn424ZFDPFktqSmQR/Qp73ZWGB0OKFk9GA9jKVJLynAXKpQdEyqdutQOkdyihdaBJLQLt/Gd4sygGbTsghWDzkZp+RU8yE=)
  iv-secret: ENC(5CDh2XgAz5nbHQZn+eotxE8rsP42g649LdfLnBVwu1qNWCmpt4VsL51DJkbwk1bv)

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
      base-path: ENC(h6Ym+FGDLXE5MmluTbjZpoC7hn6tz2e8ISzOmScqTt5daGo1bH7yrBLc00pVPDbTBbA9P3dWBzc=)
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

server-uri: http://localhost:8080
