spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lie8EE5x3EjSgzT6
            client-secret: 3026c4b08c12a31d6da2e2a1c2a815a08cc6a61b
            scope: read:user
            redirect-uri: "http://localhost:3000/api/auth/github/callback"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
    logging:
      level:
        org:
          hibernate:
            SQL: debug
            type:
              descriptor:
                sql:
                  BasicBinder: trace

logging:
  level:
    org.springframework.web: DEBUG
    com.leets.commitato: DEBUG


jwt:
  secret: 8xI1EG09dxm02J58LWj0iHEUKYPrCq0aDFXJvzZNNbSeZZl9GjlVTAjjYA4dojSPD3RBvsh0DBicyaw0hz0d7Q==